-- Generated by scripts/build-database-schema.mjs. Fresh installations only.
BEGIN;
-- Schema generator input. Deploy schema.sql, not this file alone.

-- 1. Create inquiries table
CREATE TABLE IF NOT EXISTS public.inquiries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL,
  inquiry_code TEXT NOT NULL,
  status TEXT DEFAULT 'open',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  telegram_alert_sent_at TIMESTAMP WITH TIME ZONE,
  telegram_alert_claimed_at TIMESTAMP WITH TIME ZONE,
  telegram_alert_claim_token UUID
);

ALTER TABLE public.inquiries
  ADD COLUMN IF NOT EXISTS telegram_alert_sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.inquiries
  ADD COLUMN IF NOT EXISTS telegram_alert_claimed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.inquiries
  ADD COLUMN IF NOT EXISTS telegram_alert_claim_token UUID;

CREATE UNIQUE INDEX IF NOT EXISTS inquiries_inquiry_code_key
  ON public.inquiries (inquiry_code);

-- 2. Create inquiry_messages table
CREATE TABLE IF NOT EXISTS public.inquiry_messages (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  inquiry_id UUID REFERENCES public.inquiries(id) ON DELETE CASCADE,
  sender TEXT NOT NULL, -- 'user' or 'admin'
  message TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  telegram_alert_sent_at TIMESTAMP WITH TIME ZONE,
  telegram_alert_claimed_at TIMESTAMP WITH TIME ZONE,
  telegram_alert_claim_token UUID
);

ALTER TABLE public.inquiry_messages
  ADD COLUMN IF NOT EXISTS telegram_alert_sent_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.inquiry_messages
  ADD COLUMN IF NOT EXISTS telegram_alert_claimed_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE public.inquiry_messages
  ADD COLUMN IF NOT EXISTS telegram_alert_claim_token UUID;

ALTER TABLE public.inquiries ADD COLUMN IF NOT EXISTS guest_ip TEXT;

CREATE TABLE IF NOT EXISTS public.support_admins (
  email TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Authoritative admin allowlist; never configured in the browser.
INSERT INTO public.support_admins (email)
VALUES ('cwj120408@gmail.com'), ('kimjc.120211@gmail.com')
ON CONFLICT (email) DO NOTHING;

ALTER TABLE public.support_admins ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.support_admins FROM anon, authenticated, PUBLIC;

CREATE INDEX IF NOT EXISTS inquiries_guest_ip_created_at_idx
  ON public.inquiries (guest_ip, created_at)
  WHERE user_id IS NULL;

-- 3.5 Claim a fully persisted inquiry for a server-only Telegram alert.
DROP FUNCTION IF EXISTS public.claim_inquiry_telegram_alert(uuid);
CREATE OR REPLACE FUNCTION public.claim_inquiry_telegram_alert(p_inquiry_id uuid)
RETURNS TABLE (
  id uuid,
  inquiry_type text,
  created_at timestamp with time zone,
  claim_token uuid,
  sender_name text,
  message_preview text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_claim_token uuid := gen_random_uuid();
BEGIN
  RETURN QUERY
  WITH initial_message AS (
    SELECT messages.inquiry_id, messages.message
    FROM public.inquiry_messages AS messages
    WHERE messages.inquiry_id = p_inquiry_id
      AND messages.sender = 'user'
    ORDER BY messages.created_at ASC
    LIMIT 1
  ),
  claimed AS (
    UPDATE public.inquiries AS inquiries
    SET
      telegram_alert_claimed_at = now(),
      telegram_alert_claim_token = new_claim_token
    FROM initial_message
    WHERE inquiries.id = initial_message.inquiry_id
      AND inquiries.telegram_alert_sent_at IS NULL
      AND (
        inquiries.telegram_alert_claimed_at IS NULL
        OR inquiries.telegram_alert_claimed_at < now() - interval '15 minutes'
      )
    RETURNING inquiries.id, inquiries.created_at, inquiries.user_id, inquiries.nickname, initial_message.message
  )
  SELECT
    claimed.id,
    COALESCE(NULLIF(trim((regexp_match(claimed.message, '^\[문의 유형\]\s*([^\r\n]+)', 'm'))[1]), ''), '기타'),
    claimed.created_at,
    new_claim_token,
    CASE
      WHEN claimed.user_id IS NULL THEN '비로그인 유저'
      ELSE COALESCE(NULLIF(trim(claimed.nickname), ''), '로그인 유저')
    END,
    left(
      regexp_replace(
        COALESCE(
          NULLIF(split_part(split_part(claimed.message, '[문의 내용]', 2), '[문의 목적]', 1), ''),
          claimed.message
        ),
        '^[[:space:]]+',
        ''
      ),
      5
    )
  FROM claimed;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_inquiry_telegram_alert_sent(
  p_inquiry_id uuid,
  p_claim_token uuid
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.inquiries
  SET
    telegram_alert_sent_at = now(),
    telegram_alert_claimed_at = NULL,
    telegram_alert_claim_token = NULL
  WHERE id = p_inquiry_id
    AND telegram_alert_sent_at IS NULL
    AND telegram_alert_claim_token = p_claim_token;
$$;

CREATE OR REPLACE FUNCTION public.release_inquiry_telegram_alert(
  p_inquiry_id uuid,
  p_claim_token uuid
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.inquiries
  SET
    telegram_alert_claimed_at = NULL,
    telegram_alert_claim_token = NULL
  WHERE id = p_inquiry_id
    AND telegram_alert_sent_at IS NULL
    AND telegram_alert_claim_token = p_claim_token;
$$;

REVOKE ALL ON FUNCTION public.claim_inquiry_telegram_alert(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.mark_inquiry_telegram_alert_sent(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.release_inquiry_telegram_alert(uuid, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_inquiry_telegram_alert(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_inquiry_telegram_alert_sent(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_inquiry_telegram_alert(uuid, uuid) TO service_role;

DROP FUNCTION IF EXISTS public.claim_inquiry_message_telegram_alert(uuid);
CREATE OR REPLACE FUNCTION public.claim_inquiry_message_telegram_alert(p_message_id uuid)
RETURNS TABLE (
  inquiry_id uuid,
  inquiry_type text,
  created_at timestamp with time zone,
  claim_token uuid,
  sender_name text,
  message_preview text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  new_claim_token uuid := gen_random_uuid();
BEGIN
  RETURN QUERY
  WITH claimed AS (
    UPDATE public.inquiry_messages AS messages
    SET
      telegram_alert_claimed_at = now(),
      telegram_alert_claim_token = new_claim_token
    WHERE messages.id = p_message_id
      AND messages.sender = 'user'
      AND messages.telegram_alert_sent_at IS NULL
      AND (
        messages.telegram_alert_claimed_at IS NULL
        OR messages.telegram_alert_claimed_at < now() - interval '15 minutes'
      )
    RETURNING messages.inquiry_id, messages.created_at, messages.message
  ),
  initial_message AS (
    SELECT messages.inquiry_id, messages.message
    FROM public.inquiry_messages AS messages
    JOIN claimed ON claimed.inquiry_id = messages.inquiry_id
    WHERE messages.sender = 'user'
    ORDER BY messages.created_at ASC
    LIMIT 1
  )
  SELECT
    claimed.inquiry_id,
    COALESCE(NULLIF(trim((regexp_match(initial_message.message, '^\[문의 유형\]\s*([^\r\n]+)', 'm'))[1]), ''), '기타'),
    claimed.created_at,
    new_claim_token,
    CASE
      WHEN inquiries.user_id IS NULL THEN '비로그인 유저'
      ELSE COALESCE(NULLIF(trim(inquiries.nickname), ''), '로그인 유저')
    END,
    left(
      regexp_replace(
        COALESCE(
          NULLIF(split_part(split_part(claimed.message, '[문의 내용]', 2), '[문의 목적]', 1), ''),
          claimed.message
        ),
        '^[[:space:]]+',
        ''
      ),
      5
    )
  FROM claimed
  JOIN initial_message ON initial_message.inquiry_id = claimed.inquiry_id
  JOIN public.inquiries AS inquiries ON inquiries.id = claimed.inquiry_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.mark_inquiry_message_telegram_alert_sent(
  p_message_id uuid,
  p_claim_token uuid
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.inquiry_messages
  SET
    telegram_alert_sent_at = now(),
    telegram_alert_claimed_at = NULL,
    telegram_alert_claim_token = NULL
  WHERE id = p_message_id
    AND telegram_alert_sent_at IS NULL
    AND telegram_alert_claim_token = p_claim_token;
$$;

CREATE OR REPLACE FUNCTION public.release_inquiry_message_telegram_alert(
  p_message_id uuid,
  p_claim_token uuid
)
RETURNS void
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  UPDATE public.inquiry_messages
  SET
    telegram_alert_claimed_at = NULL,
    telegram_alert_claim_token = NULL
  WHERE id = p_message_id
    AND telegram_alert_sent_at IS NULL
    AND telegram_alert_claim_token = p_claim_token;
$$;

REVOKE ALL ON FUNCTION public.claim_inquiry_message_telegram_alert(uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.mark_inquiry_message_telegram_alert_sent(uuid, uuid) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.release_inquiry_message_telegram_alert(uuid, uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_inquiry_message_telegram_alert(uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.mark_inquiry_message_telegram_alert_sent(uuid, uuid) TO service_role;
GRANT EXECUTE ON FUNCTION public.release_inquiry_message_telegram_alert(uuid, uuid) TO service_role;

-- 5. Create reports table for custom dynamic routes (e.g. notices, updates)
CREATE TABLE IF NOT EXISTS public.reports (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL, -- The custom URL path e.g. "report/update-1"
  content TEXT NOT NULL, -- Markdown content
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Existing installations: run this whole transaction after taking a DB backup.
-- Requires the existing support/Telegram tables and claim functions.


-- Avoid interpreting a timezone-less UTC timestamp a second time in the session timezone.
ALTER TABLE public.inquiries ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.inquiry_messages ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE public.reports ALTER COLUMN created_at SET DEFAULT now(), ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE public.support_admins ALTER COLUMN created_at SET DEFAULT now();

-- Supabase may grant EXECUTE directly through default privileges. Revoking
-- PUBLIC alone does not remove those grants from these service-only functions.
REVOKE ALL ON FUNCTION public.claim_inquiry_telegram_alert(uuid),
  public.mark_inquiry_telegram_alert_sent(uuid,uuid), public.release_inquiry_telegram_alert(uuid,uuid),
  public.claim_inquiry_message_telegram_alert(uuid), public.mark_inquiry_message_telegram_alert_sent(uuid,uuid),
  public.release_inquiry_message_telegram_alert(uuid,uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_inquiry_telegram_alert(uuid),
  public.mark_inquiry_telegram_alert_sent(uuid,uuid), public.release_inquiry_telegram_alert(uuid,uuid),
  public.claim_inquiry_message_telegram_alert(uuid), public.mark_inquiry_message_telegram_alert_sent(uuid,uuid),
  public.release_inquiry_message_telegram_alert(uuid,uuid) TO service_role;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon;
GRANT USAGE ON SCHEMA private TO authenticated;

CREATE OR REPLACE FUNCTION public.is_support_admin()
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT EXISTS (
    SELECT 1 FROM auth.users AS u
    JOIN public.support_admins AS a ON lower(a.email) = lower(u.email)
    WHERE u.id = (SELECT auth.uid()) AND u.email_confirmed_at IS NOT NULL
  );
$$;
REVOKE ALL ON FUNCTION public.is_support_admin() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.is_support_admin() TO authenticated;

-- Remove all prior permissive policies on these app-owned tables, including
-- policies with legacy names: permissive RLS policies are combined with OR.
DO $$ DECLARE p record; BEGIN
  FOR p IN SELECT schemaname, tablename, policyname FROM pg_policies
    WHERE schemaname = 'public' AND tablename IN
      ('reports','inquiries','inquiry_messages','support_admins')
  LOOP EXECUTE format('DROP POLICY %I ON %I.%I',p.policyname,p.schemaname,p.tablename); END LOOP;
END $$;

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiry_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_admins ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.reports, public.inquiries, public.inquiry_messages,
  public.support_admins FROM PUBLIC, anon, authenticated;

GRANT SELECT ON public.reports TO anon, authenticated;
GRANT INSERT (slug,content), UPDATE (slug,content), DELETE ON public.reports TO authenticated;
CREATE POLICY reports_public_read ON public.reports FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY reports_admin_insert ON public.reports FOR INSERT TO authenticated WITH CHECK ((SELECT public.is_support_admin()));
CREATE POLICY reports_admin_update ON public.reports FOR UPDATE TO authenticated USING ((SELECT public.is_support_admin())) WITH CHECK ((SELECT public.is_support_admin()));
CREATE POLICY reports_admin_delete ON public.reports FOR DELETE TO authenticated USING ((SELECT public.is_support_admin()));

GRANT SELECT ON public.inquiries, public.inquiry_messages TO authenticated;
GRANT UPDATE (status), DELETE ON public.inquiries TO authenticated;
GRANT INSERT (inquiry_id,sender,message) ON public.inquiry_messages TO authenticated;
CREATE POLICY inquiries_read ON public.inquiries FOR SELECT TO authenticated
  USING (user_id = (SELECT auth.uid()) OR (SELECT public.is_support_admin()));
CREATE POLICY inquiries_status ON public.inquiries FOR UPDATE TO authenticated
  USING (user_id = (SELECT auth.uid()) OR (SELECT public.is_support_admin()))
  WITH CHECK ((user_id = (SELECT auth.uid()) AND status = 'open') OR (SELECT public.is_support_admin()));
CREATE POLICY inquiries_admin_delete ON public.inquiries FOR DELETE TO authenticated USING ((SELECT public.is_support_admin()));
CREATE POLICY messages_read ON public.inquiry_messages FOR SELECT TO authenticated USING (
  EXISTS (SELECT 1 FROM public.inquiries i WHERE i.id = inquiry_id AND
    (i.user_id = (SELECT auth.uid()) OR (SELECT public.is_support_admin())))
);
CREATE POLICY messages_insert ON public.inquiry_messages FOR INSERT TO authenticated WITH CHECK (
  (sender = 'admin' AND (SELECT public.is_support_admin())) OR
  (sender = 'user' AND EXISTS (SELECT 1 FROM public.inquiries i WHERE i.id = inquiry_id AND i.user_id = (SELECT auth.uid())))
);

-- NOT VALID preserves older rows while enforcing constraints for every new write.
ALTER TABLE public.inquiries DROP CONSTRAINT IF EXISTS inquiries_valid_input;
ALTER TABLE public.inquiries ADD CONSTRAINT inquiries_valid_input CHECK (
  char_length(btrim(nickname)) BETWEEN 1 AND 80 AND status IN ('open','replied')
) NOT VALID;
ALTER TABLE public.inquiry_messages DROP CONSTRAINT IF EXISTS messages_valid_input;
ALTER TABLE public.inquiry_messages ADD CONSTRAINT messages_valid_input CHECK (
  inquiry_id IS NOT NULL AND sender IN ('user','admin') AND char_length(btrim(message)) BETWEEN 1 AND 12000
) NOT VALID;
ALTER TABLE public.reports DROP CONSTRAINT IF EXISTS reports_valid_input;
ALTER TABLE public.reports ADD CONSTRAINT reports_valid_input CHECK (
  char_length(slug) BETWEEN 1 AND 200
  AND slug ~ '^[A-Za-z0-9가-힣_-]+(/[A-Za-z0-9가-힣_-]+)*$'
  AND lower(split_part(slug,'/',1)) NOT IN ('api','_next','auth','taskboard','support','join','news','rules','history','updates','recovery-guidelines','server-mechanism')
  AND char_length(btrim(content)) BETWEEN 1 AND 200000
) NOT VALID;

-- Initialize once with recent activity so deployment does not reset quotas.
DO $$ BEGIN
  IF to_regclass('private.request_events') IS NULL THEN
    CREATE TABLE private.request_events(key text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
    CREATE INDEX request_events_key_time ON private.request_events(key,created_at);
    CREATE INDEX request_events_time ON private.request_events(created_at);
    INSERT INTO private.request_events(key,created_at)
      SELECT md5('guest-create:ip:' || btrim(guest_ip)),created_at FROM public.inquiries
      WHERE user_id IS NULL AND guest_ip IS NOT NULL AND created_at >= now() - interval '1 hour';
    INSERT INTO private.request_events(key,created_at)
      SELECT md5('message:' || inquiry_id::text),created_at FROM public.inquiry_messages
      WHERE sender='user' AND created_at >= now() - interval '10 minutes';
  END IF;
END $$;
REVOKE ALL ON private.request_events FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION private.consume_limit(scope text, actor text, maximum integer, seconds integer)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE actor_key text := md5(scope || ':' || actor);
BEGIN
  PERFORM pg_advisory_xact_lock(hashtextextended(actor_key,0));
  DELETE FROM private.request_events WHERE created_at < now() - interval '1 day';
  IF (SELECT count(*) FROM private.request_events WHERE key=actor_key
      AND created_at >= now() - make_interval(secs => seconds)) >= maximum THEN
    RAISE EXCEPTION 'Request limit exceeded' USING ERRCODE = 'P0001';
  END IF;
  INSERT INTO private.request_events(key) VALUES (actor_key);
END;
$$;
REVOKE ALL ON FUNCTION private.consume_limit(text,text,integer,integer) FROM PUBLIC,anon,authenticated;

CREATE OR REPLACE FUNCTION private.request_actor()
RETURNS text LANGUAGE sql STABLE SET search_path = '' AS $$
  SELECT coalesce(auth.uid()::text, 'ip:' || btrim(split_part(coalesce(
    nullif(current_setting('request.headers',true),'')::jsonb ->> 'x-forwarded-for','unknown'),',',1)));
$$;
REVOKE ALL ON FUNCTION private.request_actor() FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION private.validate_inquiry(nickname text, inquiry_type text, content text, purpose text)
RETURNS void LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  IF nickname IS NULL OR inquiry_type IS NULL OR content IS NULL OR purpose IS NULL
    OR char_length(btrim(nickname)) NOT BETWEEN 1 AND 80
    OR char_length(btrim(inquiry_type)) NOT BETWEEN 1 AND 80
    OR char_length(btrim(content)) NOT BETWEEN 1 AND 8000
    OR char_length(btrim(purpose)) NOT BETWEEN 1 AND 2000 THEN
    RAISE EXCEPTION 'Invalid inquiry fields' USING ERRCODE = '22023';
  END IF;
END;
$$;
REVOKE ALL ON FUNCTION private.validate_inquiry(text,text,text,text) FROM PUBLIC, anon, authenticated;

-- Replace guest RPC composite results so internal IPs/notification claim tokens
-- never appear in browser responses. The visible fields remain unchanged.
DROP FUNCTION IF EXISTS public.create_guest_inquiry(text,text,text,text);
CREATE FUNCTION public.create_guest_inquiry(p_nickname text,p_inquiry_type text,p_content text,p_purpose text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE r public.inquiries;
BEGIN
  PERFORM private.validate_inquiry(p_nickname,p_inquiry_type,p_content,p_purpose);
  PERFORM private.consume_limit('guest-create',private.request_actor(),3,3600);
  INSERT INTO public.inquiries(user_id,nickname,inquiry_code,status)
    VALUES (NULL,btrim(p_nickname),'STM-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,18)),'open') RETURNING * INTO r;
  INSERT INTO public.inquiry_messages(inquiry_id,sender,message) VALUES
    (r.id,'user','[문의 유형] ' || btrim(p_inquiry_type) || E'\n[문의 내용]\n' || btrim(p_content) || E'\n\n[문의 목적]\n' || btrim(p_purpose));
  RETURN jsonb_build_object('id',r.id,'user_id',r.user_id,'nickname',r.nickname,'inquiry_code',r.inquiry_code,'status',r.status,'created_at',r.created_at);
END;
$$;

CREATE OR REPLACE FUNCTION public.create_member_inquiry(p_nickname text,p_inquiry_type text,p_content text,p_purpose text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE r public.inquiries; member_id uuid := auth.uid();
BEGIN
  IF member_id IS NULL THEN RAISE EXCEPTION 'Authentication required' USING ERRCODE = '42501'; END IF;
  PERFORM private.validate_inquiry(p_nickname,p_inquiry_type,p_content,p_purpose);
  -- Serialize the rolling one-hour check, including pre-migration inquiries.
  PERFORM pg_advisory_xact_lock(hashtextextended('member-create:' || member_id::text,0));
  IF (SELECT count(*) FROM public.inquiries WHERE user_id = member_id AND created_at >= now() - interval '1 hour') >= 3 THEN
    RAISE EXCEPTION 'Request limit exceeded' USING ERRCODE = 'P0001';
  END IF;
  INSERT INTO public.inquiries(user_id,nickname,inquiry_code,status)
    VALUES (member_id,btrim(p_nickname),'STM-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,18)),'open') RETURNING * INTO r;
  INSERT INTO public.inquiry_messages(inquiry_id,sender,message) VALUES
    (r.id,'user','[문의 유형] ' || btrim(p_inquiry_type) || E'\n[문의 내용]\n' || btrim(p_content) || E'\n\n[문의 목적]\n' || btrim(p_purpose));
  RETURN jsonb_build_object('id',r.id,'user_id',r.user_id,'nickname',r.nickname,'inquiry_code',r.inquiry_code,'status',r.status,'created_at',r.created_at);
END;
$$;

DROP FUNCTION IF EXISTS public.get_guest_inquiry(text);
CREATE FUNCTION public.get_guest_inquiry(p_inquiry_code text)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path = '' AS $$
  SELECT jsonb_build_object('id',id,'user_id',user_id,'nickname',nickname,'inquiry_code',inquiry_code,'status',status,'created_at',created_at)
  FROM public.inquiries WHERE user_id IS NULL AND inquiry_code = upper(btrim(p_inquiry_code)) LIMIT 1;
$$;
DROP FUNCTION IF EXISTS public.get_guest_inquiry_messages(text);
CREATE FUNCTION public.get_guest_inquiry_messages(p_inquiry_code text)
RETURNS TABLE(id uuid,inquiry_id uuid,sender text,message text,created_at timestamptz)
LANGUAGE sql SECURITY DEFINER SET search_path = '' AS $$
  SELECT m.id,m.inquiry_id,m.sender,m.message,m.created_at FROM public.inquiry_messages m
  JOIN public.inquiries i ON i.id=m.inquiry_id WHERE i.user_id IS NULL AND i.inquiry_code=upper(btrim(p_inquiry_code))
  ORDER BY m.created_at ASC;
$$;
DROP FUNCTION IF EXISTS public.send_guest_inquiry_message(text,text);
CREATE FUNCTION public.send_guest_inquiry_message(p_inquiry_code text,p_message text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE inquiry uuid; m public.inquiry_messages;
BEGIN
  IF p_message IS NULL OR char_length(btrim(p_message)) NOT BETWEEN 1 AND 12000 THEN
    RAISE EXCEPTION 'Invalid message' USING ERRCODE = '22023';
  END IF;
  SELECT id INTO inquiry FROM public.inquiries WHERE user_id IS NULL AND inquiry_code=upper(btrim(p_inquiry_code));
  IF inquiry IS NULL THEN RAISE EXCEPTION 'Invalid inquiry' USING ERRCODE = '22023'; END IF;
  INSERT INTO public.inquiry_messages(inquiry_id,sender,message) VALUES (inquiry,'user',btrim(p_message)) RETURNING * INTO m;
  RETURN jsonb_build_object('id',m.id,'inquiry_id',m.inquiry_id,'sender',m.sender,'message',m.message,'created_at',m.created_at);
END;
$$;
REVOKE ALL ON FUNCTION public.create_guest_inquiry(text,text,text,text),public.get_guest_inquiry(text),public.get_guest_inquiry_messages(text),public.send_guest_inquiry_message(text,text),public.create_member_inquiry(text,text,text,text) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_guest_inquiry(text,text,text,text),public.get_guest_inquiry(text),public.get_guest_inquiry_messages(text),public.send_guest_inquiry_message(text,text) TO anon,authenticated;
GRANT EXECUTE ON FUNCTION public.create_member_inquiry(text,text,text,text) TO authenticated;

-- Limits apply to direct authenticated inserts as well as guest RPCs. Status
-- updates share the message transaction, so failed writes never leave stale state.
CREATE OR REPLACE FUNCTION private.guard_message()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  IF NEW.sender = 'user' THEN
    PERFORM private.consume_limit('message',NEW.inquiry_id::text,30,600);
  END IF;
  UPDATE public.inquiries SET status = CASE WHEN NEW.sender='admin' THEN 'replied' ELSE 'open' END,
    updated_at=now() WHERE id=NEW.inquiry_id;
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION private.guard_message() FROM PUBLIC,anon,authenticated;
DROP TRIGGER IF EXISTS guard_message ON public.inquiry_messages;
CREATE TRIGGER guard_message AFTER INSERT ON public.inquiry_messages FOR EACH ROW EXECUTE FUNCTION private.guard_message();

-- A fresh schema is generated with these same policies. No realtime publication
-- is dropped here; existing subscriptions and unrelated tables remain intact.
NOTIFY pgrst, 'reload schema';


-- Removes the retired server join request feature and all stored applications.


DROP FUNCTION IF EXISTS public.get_stimemc_join_requests();
DROP FUNCTION IF EXISTS public.complete_stimemc_join_request(uuid);
-- Dropping the table also removes its policies, indexes and trigger.
DROP TABLE IF EXISTS public.join_requests;
DROP FUNCTION IF EXISTS private.guard_join_request();
DROP FUNCTION IF EXISTS private.is_stimemc_admin();

NOTIFY pgrst, 'reload schema';


-- BEGIN REALTIME SETUP (logical replication is absent in the embedded test DB)
DO $$
DECLARE target text;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
  FOREACH target IN ARRAY ARRAY['inquiries','inquiry_messages','reports'] LOOP
    IF NOT EXISTS (SELECT 1 FROM pg_publication_tables WHERE pubname='supabase_realtime' AND schemaname='public' AND tablename=target) THEN
      EXECUTE format('ALTER PUBLICATION supabase_realtime ADD TABLE public.%I',target);
    END IF;
  END LOOP;
END $$;
-- END REALTIME SETUP

COMMIT;
